site_name: point-zero.one
site_url: https://point-zero.one
repo_url: https://github.com/DataEnggNerd/point-zero-one
repo_name: point-zero-one

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    primary: deep purple
    accent: teal
    # Palette toggle for light mode
  features:
  - content.code.copy
  - content.code.select
  - navigation.footer
  - navigation.indexes
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow

nav:
  - point-zero-one: index.md
  - Random Notes: notes/index.md
  - My Stuff: my-stuff/index.md

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde